# Generated by Django 5.2.6 on 2025-09-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='show_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='header',
            name='show_signup',
            field=models.BooleanField(default=True),
        ),
    ]
