# Generated by Django 5.2.6 on 2025-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_header_show_login_header_show_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(max_length=50)),
                ('sub_para', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_para', models.CharField(max_length=100)),
                ('box_icon', models.URLField(max_length=100)),
                ('box_heading', models.CharField(max_length=50)),
                ('box_para', models.CharField(max_length=200)),
            ],
        ),
    ]
