# Generated by Django 5.2.6 on 2025-09-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_hero_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='box_icon',
        ),
        migrations.AddField(
            model_name='works',
            name='icon_class',
            field=models.CharField(default='fa fa-star', help_text='Enter icon class e.g. fa fa-home or bi bi-house', max_length=100),
            preserve_default=False,
        ),
    ]
