# Generated by Django 5.2.6 on 2025-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_works_box_icon_works_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkBoxex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Enter icon class e.g. fa fa-home or bi bi-house', max_length=100)),
                ('box_heading', models.CharField(max_length=50)),
                ('box_para', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='works',
            name='box_heading',
        ),
        migrations.RemoveField(
            model_name='works',
            name='box_para',
        ),
        migrations.RemoveField(
            model_name='works',
            name='icon_class',
        ),
    ]
