# Generated by Django 5.2.6 on 2025-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_workboxex_remove_works_box_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_para', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExploreBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Enter icon class e.g. fa fa-home or bi bi-house', max_length=100)),
                ('box_heading', models.CharField(max_length=50)),
                ('box_para', models.CharField(max_length=200)),
            ],
        ),
    ]
