# Generated by Django 5.2.6 on 2025-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_explore_exploreboxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_para', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpotsBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_heading', models.CharField(max_length=50)),
                ('box_para', models.CharField(max_length=200)),
            ],
        ),
    ]
