# Generated by Django 5.2.6 on 2025-09-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_spots_spotsboxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_para', models.CharField(max_length=100)),
                ('child_heading', models.CharField(max_length=50)),
                ('child_para', models.CharField(max_length=200)),
                ('button_url', models.URLField()),
                ('button_text', models.URLField()),
            ],
        ),
    ]
