# Generated by Django 5.2.6 on 2025-09-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_ctasection'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='button_text',
            field=models.CharField(default='button 1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='button_text_2',
            field=models.CharField(default='button', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='button_text',
            field=models.CharField(max_length=200),
        ),
    ]
