# Generated by Django 5.2.6 on 2025-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_hero_button_text_hero_button_text_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='button_text',
            field=models.CharField(default='Get Started Now', max_length=200),
            preserve_default=False,
        ),
    ]
