# Generated by Django 5.2.6 on 2025-10-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_footerbrand_footersection_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_heading', models.CharField(max_length=50)),
                ('para', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Enter icon class e.g. fa fa-home or bi bi-house', max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('para', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoreValuesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_heading', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('para', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Enter icon class e.g. fa fa-home or bi bi-house', max_length=100)),
                ('stats_num', models.CharField(max_length=50)),
                ('title', models.CharField(default='Our Core Values', max_length=50)),
            ],
        ),
    ]
