# Generated by Django 5.2.6 on 2025-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_about_corevalue_corevaluessection_pagetitle_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='icon_class',
            field=models.CharField(default='fas fa-map-pin', help_text='Enter icon class e.g. fa fa-home or bi bi-house', max_length=100),
        ),
    ]
