# Generated by Django 5.2.6 on 2025-10-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_gallerybreadcrumb_galleryimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerybreadcrumb',
            old_name='short_description',
            new_name='para',
        ),
    ]
