# Generated by Django 5.2.6 on 2025-10-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='category',
            name='class_name',
            field=models.CharField(default='short description', help_text='Enter icon class e.g. fa fa-home or bi bi-house', max_length=50),
            preserve_default=False,
        ),
    ]
