# Generated by Django 5.2.6 on 2025-10-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_short_description_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
